from core.desired_velocity_providers.wandering import Wandering
from core.desired_velocity_providers.edge_evading import EdgeEvading
from core.desired_velocity_providers.escaping import AbstractEscaping
